FROM quay.io/modh/odh-generic-data-science-notebook:v2-20240215
WORKDIR /app
COPY ./openjourney .
USER 0
RUN dnf update -y && \
    dnf install -y python3-pip && \
    pip install -r requirements.txt && \
    pip install -q --extra-index-url https://download.pytorch.org/whl/cpu "diffusers[torch]>=0.9.0" && \
    dnf clean all && \
    chown 1001:1001 /app
USER 1001
RUN python3 init.py
ENTRYPOINT ["python3", "run.py"]
