FROM quay.io/opendatahub-contrib/workbench-images:cuda-runtime-pytorch-c9s-py311_2023c_latest
COPY ./openjourney .
RUN pip3 install -r requirements.txt
RUN git-lfs install && git clone https://huggingface.co/runwayml/stable-diffusion-v1-5 /opt/app-root/src/model
ENTRYPOINT ["python3", "run.py"]
