FROM quay.io/fedora/fedora:39 as builder
RUN curl https://sh.rustup.rs -sSf | sed 's#/proc/self/exe#\/bin\/sh#g' | sh -s -- -y
ENV PATH "$PATH:/root/.cargo/bin"
RUN rustup target add wasm32-unknown-unknown \
    && curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash \
    && cargo binstall trunk --no-confirm \
    && dnf install -y /usr/bin/cc \
    && dnf clean all

WORKDIR /src
COPY . .
ENV PRODUCTION true
RUN cd ui/ && trunk build --release

FROM quay.io/packit/nginx-unprivileged:1.23.4

COPY --from=builder /src/dist /app
COPY --from=builder /src/ui/nginx.conf /etc/nginx/conf.d/ui.conf
RUN rm -rf /etc/nginx/conf.d/default.conf

EXPOSE 9090
