kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: openjourney
  namespace: ai-prompt
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'openshift-ai-prompt:openjourney'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.openjourney
      imageOptimizationPolicy: SkipLayers
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/vrutkovs/openshift-ai-prompt.git'
    contextDir: /
  runPolicy: Serial
