[package]
name = "openshift-ai-prompt-common"
version = "0.1.0"
authors = ["Vadim Rutkovsky <vadim@vrutkovs.eu>"]
edition = "2021"

[dependencies]
serde = "1.0"
serde_json = "1.0"
anyhow = "1.0.71"
reqwasm = "0.5.0"
enum-iterator = "2.0.0"
lazy_static = "1.4.0"
